Adding POST provider functionality
Lambda-School-Labs/family-promise-service-tracker-be-a pull request #112
Opened 2021-07-14 23:02 UTC by hans0

# Description

Set up POST provider API endpoint

## What work was done?

Got rid of the stub 

## Why was this work done?

To give the administrators the ability to add future providers/employees

## Type of change

New feature 

## Change Status

In progress

## Checklist

- [ ] Endpoint tested with Postman, or Unit test.
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings
- [X] There are no merge conflicts

2021-07-26 18:06 UTC, LoganTilley commented
Your pull request template says that this is still in progress - is it still in progress?

2021-07-27 20:36 UTC, LittleBoGeek requested changes
I count several console logs from lines 47 - 58. Typically best practice is to remove console logs before merging into main. But it seems like they were left to show the next cohort how to access the object properly? If that's the case and they're just demonstrative, is it possible to remove the console logs and add that information into the repo documentation?

2021-07-27 21:30 UTC, LittleBoGeek approved these changes

2021-07-30 15:39 UTC, VinceRyanGarcia commented
Thanks for cleaning up the console logs, Hans. Looks good!

2021-07-30 15:59 UTC, merged