removed db-helper, replaced db-helper in service type, statuses, serv…
Lambda-School-Labs/family-promise-service-tracker-be-a pull request #123
Opened 2021-08-19 17:41 UTC by ErikBurdett

…ice entries and recipients and left skeleton functions in respective models.

# Description

Summary of your changes
removed db-helper, replaced db-helper in service type, statuses, service entries and recipients and left skeleton functions in respective models. Also commented anywhere I found db-helper out. 

## What work was done?
removed db-helper, replaced db-helper in service type, statuses, service entries and recipients and left skeleton functions in respective models.

Details of your changes

## Why was this work done?
to prepare for database changes.

Why?
Fixing models and routers for database and removing db-helper

## Type of change

- New feature (non-breaking change which adds functionality)?
- Bug Fix?

## Change Status

- Completed, ready to review and merge?
- In progress?
- etc.

## Checklist

- [] Endpoint tested with Postman, or Unit test.
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] My changes generate no new warnings
- [x ] There are no merge conflicts

2021-08-19 17:53 UTC, chance10113 approved these changes
Looks good, necessary skeletonization work done.

2021-08-19 17:59 UTC, ahmedseragcodes reviewed
I thought the idea was to leave the respective modeling for each section (programs, service types, service entries) and remove the DB-helper that generalizes modeling for all of these? No?

2021-08-19 18:22 UTC, santorap requested changes
Good updates here Erik.

The .env.sample file was deleted but I think we want to keep it in there as an example during setup.

One minor question I have is regarding some of the commented out code you have in the first few files. Is there any reason we can't just delete those single lines outright?

Also, I'd prefer if someone more familiar with the needed changes here takes a closer look at `recipientModel.js`, `serviceEntriesModel.js`, and `serviceTypeModel.js`. I understand we are skeletonizing a lot of this, but some of that stuff looks like it will be substantially similar once the new tables are built.

Is it better to leave them mostly empty like you have it or should we try to keep some of it if it will work under the new structure? If it is the latter then I'll rely on your judgement for that!

2021-08-19 18:22 UTC, santorap commented on .env.sample
> -DEV_DATABASE_URL=postgres://docker:docker@127.0.0.1:5400/api-dev
We likely want to remove the 2nd "docker" in line 4 and 5, but I think the instructions for setup reference this file as an example. Probably not a good idea to remove the file altogether.

2021-08-19 18:22 UTC, santorap commented on api/household/householdRouter.js
> +// const DB = require('../utils/db-helper');
If we _know_ we won't be using the old `db-helper` code, we should probably remove the code outright, not comment it out.

2021-08-19 18:22 UTC, santorap commented on api/location/locationRouter.js
> +// const DB = require('../utils/db-helper');
Same as my comment in the householdRouter.js file, why comment it out when it is no longer needed and can be removed?

2021-08-19 18:22 UTC, santorap commented on api/middleware/authRequired.js
> +// const DB = require('../utils/db-helper');
Ditto to householdRouter.js and locationRouter.js.

2021-08-19 18:22 UTC, santorap commented on api/program/programRouter.js
> +// const DB = require('../utils/db-helper');
This one too.

2021-08-19 18:22 UTC, santorap commented on api/recipient/recipientRouter.js
> +  Recipients.update(req.params.id, req.body)
These changes look great!

2021-08-19 18:22 UTC, santorap commented on api/household/householdRouter.js
> +// const DB = require('../utils/db-helper');
Kind of like what you did in `serviceEntriesRouter.js`.

2021-08-19 18:22 UTC, santorap commented on api/serviceEntries/serviceEntriesRouter.js
> +  ServiceEntries.update(req.params.id, req.body)
These changes look good!

2021-08-19 18:22 UTC, santorap commented on api/serviceTypes/serviceTypeRouter.js
> +  ServiceTypes.remove('service_types', id)
These changes look good!

2021-08-19 18:22 UTC, santorap commented on api/statuses/statusesModel.js
> +};
🦴☠🦴

2021-08-19 18:22 UTC, santorap commented on api/statuses/statusesRouter.js
> +  Statuses.remove(id)
Good updates!

2021-08-24 16:19 UTC, santorap commented
Michael's recent pull requests supersede these updates. No need to push them any longer.

2021-08-24 16:19 UTC, closed without merging