added new migrations tables according to an agreed upon schema: https…
Lambda-School-Labs/family-promise-service-tracker-be-a pull request #59
Opened 2021-06-09 20:51 UTC by Monicascz

…://app.dbdesigner.net/designer/schema/0-schema-w-json-family-promise-labs-35

The following tables were added:
-Recipients
-Genders
-Races
-Ethnicities
-Service_Entry_Providers

These migrations were added to accommodate the adjustments we made to our table layout as a team. The benefit of this new structure is that it allows for program managers of Family Promise to be able to add their own parameters for the field names in these various tables.

2021-06-09 23:53 UTC, jaypdl requested changes

2021-06-09 23:53 UTC, jaypdl commented on data/newMigrations/010-recipients.js
> +        tbl.int('gender_id')
Mistake on the schema on my part! Everywhere where it says int in the schema, you should actually be using `.integer` not `.int`. I don't think `.int` is a valid knex command.;

2021-06-09 23:53 UTC, jaypdl commented on data/newMigrations/010-recipients.js
> +        tbl.string('recipient_first_name');
Can you add `.notNullable()` to all of these except middle name?

2021-06-09 23:53 UTC, jaypdl commented on data/newMigrations/014-service_entry_provider.js
> +        tbl.increments('service_entry_provider_id').primary();
In this case, when using `.increments()`, knex will automatically set this as a primary key, so you don't need `.primary()`.

2021-06-09 23:53 UTC, jaypdl commented on data/newMigrations/014-service_entry_provider.js
> +        tbl.int('provider_id')
Switch the `.int` to `.integer` and add `.notNullable` to service_entry_id and provider_id

2021-06-09 23:53 UTC, jaypdl commented on data/newMigrations/016-genders.js
> +        tbl.increments('gender_id').primary();
`.primary()` is not needed, when using `.increments()` knex sets it as primary behind the scenes

2021-06-09 23:53 UTC, jaypdl commented on data/newMigrations/017-races.js
> +        tbl.increments('race_id').primary();
`.primary()` is not needed, when using `.increments()` knex sets it as primary behind the scenes

2021-06-09 23:53 UTC, jaypdl commented on data/newMigrations/018-ethnicities.js
> +        tbl.increments('ethnicity_id').primary();
`.primary()` is not needed, when using `.increments()` knex sets it as primary behind the scenes

2021-06-09 23:53 UTC, jaypdl commented on data/newMigrations/016-genders.js
> +        tbl.string('gender');
Please add `.notNullable()`

2021-06-09 23:53 UTC, jaypdl commented on data/newMigrations/017-races.js
> +        tbl.string('race');
Please add `.notNullable()`

2021-06-09 23:53 UTC, jaypdl commented on data/newMigrations/018-ethnicities.js
> +        tbl.string('ethnicity');
Please add `.notNullable()`

2021-06-09 23:55 UTC, jaypdl commented
Awesome job! Just a few changes. Sorry about the `.int` confusion!

2021-06-10 15:50 UTC, MatthewEllisTx commented
Maybe break up the commit so it's one commit/migration file

2021-06-10 15:52 UTC, Monicascz reviewed
Thank you for the thoughtful feedback! I have reviewed these changes and will be doing another PR.

2021-06-10 19:36 UTC, closed without merging